import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/appSidebar";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/providers/themeprovider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import { PageHeaderProvider } from "@/contexts/PageHeaderContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FulCrum - Warehouse & Inventory Management",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange={false}>
          <SidebarProvider defaultOpen={defaultOpen}>
            <Sidebar />
            <PageHeaderProvider>
              <main className="w-full">
                <Navbar />
                <div className="px-4"> {children}</div>
              </main>
            </PageHeaderProvider>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
